// Package envtemplate generates a .env.template file from one or more parsed env maps.
// Keys are preserved; values are replaced with empty or placeholder strings.
package envtemplate

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// Options controls template generation behaviour.
type Options struct {
	// Placeholder is written as the value for every key.
	// If empty, values are left blank (KEY=).
	Placeholder string
	// IncludeComments adds a header comment to the output file.
	IncludeComments bool
}

// Generate merges keys from all supplied env maps and returns a sorted
// slice of "KEY=<placeholder>" lines ready to be written to a file.
func Generate(envMaps []map[string]string, opts Options) []string {
	seen := make(map[string]struct{})
	for _, m := range envMaps {
		for k := range m {
			seen[k] = struct{}{}
		}
	}

	keys := make([]string, 0, len(seen))
	for k := range seen {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	lines := make([]string, 0, len(keys)+3)
	if opts.IncludeComments {
		lines = append(lines,
			"# Auto-generated by envdiff — do not store real secrets here.",
			"",
		)
	}

	for _, k := range keys {
		lines = append(lines, fmt.Sprintf("%s=%s", k, opts.Placeholder))
	}
	return lines
}

// Write generates a template and writes it to the given file path.
func Write(path string, envMaps []map[string]string, opts Options) error {
	lines := Generate(envMaps, opts)
	content := strings.Join(lines, "\n") + "\n"
	return os.WriteFile(path, []byte(content), 0o644)
}
